version: 2
jobs:
  build_python:
    docker:
      -
        image: 'debian:stretch'
    steps:
      - checkout
      -
        run:
          name: 'Install build essentials'
          command: "apt-get update && apt-get -y install wget make curl gcc g++ libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libffi-dev"
      -
        run:
          name: 'Make Python'
          command: 'make circle_ci_build PYTHON_VERSION=3.8.0 PYTHON_SUB_VERSION=a1 PYTHON_MAKE_DIR=/tmp/temp_py_make_dir'
      - 
        run:
          name: 'Publish to Github'
          command: |
            mkdir -p /tmp/ghr_dl
            cd /tmp/ghr_dl
            wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz
            tar -xf ghr_v0.12.0_linux_amd64.tar.gz
            cd /tmp/temp_py_make_dir/Python-*
            VERSION=$(/tmp/temp_py_make_dir/python --version) 
            cd /tmp/ghr_dl/ghr_v0.12.0_linux_amd64 && ./ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/temp_py_make_dir"
workflows:
  version: 2
  build:
    jobs:
      - build_python
