version: 0.1
jobs:
  publish-github-release:
    docker:
      -
        image: 'cibuilds/github:0.10'
    steps:
      -
        attach_workspace:
          at: /root/project
      -
        run:
          name: 'Publish Release on GitHub'
          command: "VERSION=$(python --version)\nghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /root/project\n"
