version: 2
jobs:
  build_python:
    docker:
      -
        image: 'debian:stretch'
    steps:
      - checkout
      -
        run:
          name: 'Install build essentials'
          command: "apt-get update && apt-get -y install git-core golang make curl gcc g++ libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libffi-dev"
      #-
        #run:
          #name: 'Make Python'
          #command: 'make circle_ci_build PYTHON_VERSION=3.8.0 PYTHON_SUB_VERSION=a1 PYTHON_MAKE_DIR=/tmp/temp_py_make_dir'
      -
        run:
          name: 'Setup Golang'
          command: |
            mkdir -p ${GOPATH} ${GOBIN} ${GOPKG} ${GOSRC}
      -
        run:
          name: 'Build GHR'
          command: |
            go get -u github.com/tcnksm/ghr
            cd $GOSRC/github.com/tcnksm/ghr && go build
      - 
        run:
          name: 'Publish to Github'
          command: |
            VERSION=$(python --version) 
            cd $GOSRC/github.com/tcnksm/ghr && ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/temp_py_make_dir"
workflows:
  version: 2
  build:
    jobs:
      - build_python
