version: 0.1
jobs:
  build:
    docker:
      -
        image: 'debian:stretch'
    steps:
      - checkout
      -
        run:
          name: 'Install build essentials'
          command: 'apt-get update && apt-get -y install make curl libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libffi-dev'
      -
        run:
          name: 'Make Python'
          command: 'make circle_ci_build PYTHON_VERSION=3.8.0 PYTHON_SUB_VERSION=a1 PYTHON_MAKE_DIR=/tmp/temp_py_make_dir'
